### ISSUE TITLE
Issues in the comments thread (2)

### ISSUE THREAD

**Issue by krnekhelesh** [nikwen/forum-app#5]
I see 2 potential issues in the comments thread shown in the screenshot below,
- It could use some automatic formatting of text within [quote][/quote] tags
- The comment text shouldn't be aligned to the right of the image but should rather take the full width of the comment box (wishlist)

My reasoning for the 2nd issue is that on the phone the width and height are precious resources. By making the comment text to take the full width you reduce the scrolling required and also best utilise the space.

![forums-app-bug2](https://cloud.githubusercontent.com/assets/761845/4153701/68eb397a-345b-11e4-8829-6ad90300905c.png)

**Comment by nikwen** [comment]
Just to give you an update. I'm currently working on both issues you mentioned. Those are very complex changes though so it's taking a long time.
Current work item: https://github.com/nikwen/forum-app/issues/38

**Comment by nikwen** [comment]
Hi Nekhelesh,

The implementation is finally ready and an update should be available in the store very soon. You'll see an announcement in the Ubuntu App Developer community on G+ when it is available.

Thank you very much again for your ideas!

Cheers,
Niklas
